spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anlucki/dh-clase10-configuration
          default-label: master

server:
  port: 8888